### ISSUE TITLE
Validation failed in datafactory artifacts

### ISSUE THREAD

**Issue by Logeswari25** [Azure/data-factory-validate-action#9]
Hi,

I encountered an error during the validation of Data Factory artifacts while deploying the pipeline. It is successful in ADF validate all option but failure in git validate option.

![ADF_ValidationErrror](https://github.com/Azure/data-factory-validate-action/assets/149675131/a29a43bc-243b-43e7-b79c-3fac6f0d700d)

![ADF_validationFailed](https://github.com/Azure/data-factory-validate-action/assets/149675131/43368098-eb64-40e3-a516-a7c896c3c4d3)

below is the workflow:

validate_adf:
runs-on: self-hosted
steps:
- uses: actions/checkout@v3
- name: Validate Data Factory resources
uses: Azure/data-factory-validate-action@v1.1.5
with:
path: datafactory/

Can you please assist me with this?

**Comment by pratip22** [comment]
I am also facing the same issue

**Comment by Logeswari25** [comment]
I am using this one for 7 months only.. I am not sure when it has created

**Comment by davhel** [comment]
same issue here. Using action since > 2 years

**Comment by PrajnaJena15** [comment]
@davhel   Are you saying  you have been using same action for more than 2 yr  ?  With Existing issue

**Comment by davhel** [comment]
> @davhel Are you saying you have been using same action for more than 2 yr ? With Existing issue

No, same condition like @jbdekker

**Comment by PrajnaJena15** [comment]
@davhel ok .. did u find any solutions to it ?

**Comment by davhel** [comment]
@PrajnaJena15 no, issue started today, still investigating and trying to remediate. Is this the likely solution #8 ?

**Comment by PrajnaJena15** [comment]
@davhel   above solution is for note js version change. but in workflow step of validation  node js is not used.

 this is the code snippet

uses: actions/checkout@v3
name: Validate Data Factory resources
uses: Azure/data-factory-validate-action@v1.1.5
with:
path: datafactory/

**Comment by gn-nachx** [comment]
Have you tried using a previous version? I'm dealing with the same issue

**Comment by jc-theY** [comment]
I am also having the same issue

**Comment by Logeswari25** [comment]
Is anyone found solution?

**Comment by PrajnaJena15** [comment]
@gn-nachx .. did u try the previous version and it resolve the issue?

**Comment by gn-nachx** [comment]
@PrajnaJena15 unfortunately no lol, I think there is a problem with the nodejs version because is still using version 16, and the action recommend you to use a 18.x version. But internally is still using the previous one

**Comment by j-chao** [comment]
https://github.com/Azure/data-factory-validate-action/pull/8 was just merged, and v1.1.6 fixes this issue.
